# 使用「启用 UART1 的 ps7_init」+「带 AXI GPIO 的旧比特流」加载内核
#
# 关键点:ps7_init 管 PS(时钟/MIO/DDR),比特流管 PL(AXI GPIO -> LED),
# 两者相互独立,可以交叉组合。这样既能拿到串口,又不丢 LED。
#
# 用法: 先 `python config.py` 生成 paths.tcl,再 xsdb run_kernel_uart.tcl

# ---- 本机路径:由仓库根目录的 config.py 生成,换机器只改那一个文件 ----
# 改了 config.py 之后重跑 `python config.py` 刷新 paths.tcl。
set _paths [file join [file dirname [info script]] paths.tcl]
if {![file exists $_paths]} {
    puts "FAIL: cannot find $_paths"
    puts "      It is the per-machine path table, generated by <repo>/config.py:"
    puts "          python config.py"
    exit 2
}
source $_paths

proc step {m} { puts "\n>>> $m" }
proc rd {a} {
    if {[catch {mrd -force $a} v]} { return "ERR" }
    set s [string trim $v]
    set i [string first ":" $s]
    if {$i >= 0} { return [string trim [string range $s [expr {$i+1}] end]] }
    return $s
}
# 数值版读寄存器。用 scan 而不是 expr {0x...}:
# expr 对 mrd 返回的异常文本(而非纯十六进制)会直接报错,
# 而 scan 解析失败时返回 0,可以稳妥地兜到 -1。
proc rdn {a} {
    set s [rd $a]
    if {[string equal $s "ERR"]} { return -1 }
    if {[scan $s %x n] != 1} { return -1 }
    return $n
}

# 判断"读到的是不是零"。直接做字符串比较,绕开进制解析 ——
# 早期轮询只关心"还没写" 与 "写了非零" 两种状态。
proc is_zero {s} {
    if {[string equal $s "ERR"]} { return 0 }
    if {[string equal $s "00000000"]} { return 1 }
    if {[scan $s %x n] != 1} { return 0 }
    return [expr {$n == 0}]
}

# 读 ARM 核心寄存器。用 catch 包住:不是所有版本都能读 DFAR/IFAR,
# 读不到时应当继续往下走而不是中断整段验证。
proc rr {reg} {
    if {[catch {rrd $reg} v]} { return "n/a" }
    set v [string trim $v]
    if {[llength $v] >= 2} { return [lindex $v 1] }
    return $v
}

step "connect"
if {[catch {connect} e]} { puts "FAIL connect: $e"; exit 1 }
puts "OK"

step "reset system"
if {[catch {targets -set -filter {name =~ "APU"}} e]} { puts "FAIL: 找不到 APU,板子可能需断电重启"; exit 1 }
rst -system
after 2000
puts "OK"

step "ps7_init (来自 opjtmp.xsa,已启用 UART1)"
targets -set -filter {name =~ "APU"}
if {[catch {source $PS7} e]} { puts "FAIL source: $e"; exit 1 }
if {[catch {ps7_init} e]}    { puts "FAIL ps7_init: $e"; exit 1 }
if {[catch {ps7_post_config} e]} { puts "FAIL post_config: $e"; exit 1 }
puts "OK"

# 前置校验:MIO bank 1 必须是 LVCMOS18。
#
# 本板 bank 1 实际供电 1.8V(VCCIO_BANK1 -> VCC1P8)。若 XSA 把它声明成 3.3V,
# ps7_init 会给 MIO16-53 写下 [11:9]=3(LVCMOS33) —— 那时 MIO49(UART1 RX) 的
# 输入阈值约 2.0V,而 CH9102F 只能驱动到 1.8V,引脚恒读低、没有下降沿,
# **UART 一个字节都收不到,且没有任何报错**,和"线断了"完全不可区分。
# 这个坑真实发生过,所以这里做成硬断言:配置不对就当场失败,不再往下走。
step "校验 MIO bank1 是否为 LVCMOS18"
if {[catch {source $MIOCHK} e]} { puts "FAIL source miochk: $e"; exit 1 }
set mio_bad [ps7_mio_bank1_check]
if {$mio_bad == 0} {
    puts "OK  MIO16-53 全部为 LVCMOS18"
} else {
    puts "FAIL:有 $mio_bad 个 MIO16-53 不是 LVCMOS18(bank 1 应为 1.8V):"
    ps7_mio_bank1_report
    puts ""
    puts "  这是 XSA 的 PS7 配置问题,不是内核问题。请重新导出 XSA 并把"
    puts "  MIO bank 1 的电压设成 1.8V。临时补偿可用 ps7_mio_bank1_18v_fixup。"
    exit 1
}

puts ""
puts "=== 关键寄存器核对 ==="
puts "MIO_PIN_48  = 0x[rd 0xF80007C0]   (期望 000016E0 = UART1_TX)"
puts "MIO_PIN_49  = 0x[rd 0xF80007C4]   (期望 000016E1 = UART1_RX)"
puts "APER_CLK    = 0x[rd 0xF800012C]"
puts "UART_CLK    = 0x[rd 0xF8000154]"
puts "UART1 MR    = 0x[rd 0xE0001004]   <== 非 0 就说明 UART1 活了"

step "load bitstream (AXI GPIO -> LED)"
targets -set -filter {name =~ "xc7z020"}
if {[catch {fpga -f $BIT} e]} { puts "FAIL fpga: $e"; exit 1 }
puts "OK"

step "download kernel"
targets -set -filter {name =~ "ARM*#0"}
rst -processor
if {[catch {dow $ELF} e]} { puts "FAIL dow: $e"; exit 1 }
puts "OK  PC = [lindex [rrd pc] 1]"

# 清空心跳区(0x20000..0x2003F)。
#
# 为什么必须做:OCM 不会被 rst -processor 清零,上一次运行留下的 magic
# 会让下面"等 magic 出现"的轮询立刻命中,于是在新内核还没走到写心跳之前
# 就把整片区域读成 0 —— 看上去像"内核卡住了",其实是读了残影。
# 这个坑真实发生过:串口上主循环明明在跑,JTAG 却报 loop=0/ticks=0。
step "clear heartbeat (防陈旧数据)"
for {set a 0x00020000} {$a <= 0x0002003C} {incr a 4} {
    mwr -force $a 0
}
puts "OK"

step "run"
con

step "wait for heartbeat"
set magic [rd 0x00020000]
for {set i 0} {$i < 20} {incr i} {
    after 250
    set magic [rd 0x00020000]
    if {[string match "*4F583338*" $magic]} { break }
}
puts "magic    = $magic"

# 仅仅"magic 出现"不代表可以读整片心跳区。
#
# magic 在 kmain 开头就写了,而 DIRM0/TICKS/IRQCOUNT 分别在横幅之后、
# 中断起来之后才写。9600 波特下横幅本身要 ~870ms,所以"看到 magic 立刻读"
# 会稳定地读到一片 0 —— 曾经据此误判成"内核卡在 uart_puts"。
# 这里改成等真正代表子系统起来的信号:周期 tick 计数非 0。
step "wait for IRQ subsystem (ticks != 0)"
set ticks_raw "00000000"
for {set i 0} {$i < 40} {incr i} {
    after 250
    set ticks_raw [rd 0x00020028]
    if {![is_zero $ticks_raw]} { break }
}
puts "ticks    = $ticks_raw"

# 再多给一点时间,让主循环跑几轮,把 LOOP/GT/SW 等槽位填上
after 1500

puts "loop     = [rd 0x00020004]"
puts "pl_led   = [rd 0x00020008]"
puts "gt       = [rd 0x00020010]"
puts "uart_clk = [rd 0x00020018]"
puts "dirm0    = [rd 0x0002001C]"
puts "uartok   = [rd 0x00020020]"
puts "measbaud = [rd 0x00020024]"
puts "ticks    = [rd 0x00020028]"
puts "irqcount = [rd 0x0002002C]"
puts "clksrc   = [rd 0x00020030]   <== 1=闭环收敛 2=兜底猜值"
puts "conviter = [rd 0x00020034]   <== 闭环迭代次数,0 表示没进迭代"
puts "baudgen  = [rd 0x00020038]"
puts "bauddiv  = [rd 0x0002003C]"
puts "mmustage = [rd 0x00020040]   <== MMU: 0=未开始 1=已建表 2=已配 3=正要开 4=已开 0xEE=自检失败"
puts "ledcheck = [rd 0x00020054]   <== AXI GPIO 写回读失配数;0=全对 0xFFFFFFFF=驱动没 probe 上"

# 交叉校验:ticks 应当约等于 uptime(ms),两者不符说明有中断被吞
set t [rdn 0x00020028]
set q [rdn 0x0002002C]
puts ""
puts ">>> ticks=$t irqcount=$q"
if {$t > 0 && $t == $q} {
    puts ">>> 1kHz tick 与 GIC 转发计数一致,零丢失"
} elseif {$t > 0} {
    puts ">>> 警告: ticks 与 irqcount 不一致,可能有中断未 EOI"
} else {
    puts ">>> 警告: 始终没有 tick,中断子系统未起来"
}

set u [rd 0x00020020]
puts ""
if {[string match "*00000001" $u]} {
    puts ">>> UART 已被内核探测到 —— 请看串口终端是否出现启动横幅"
} else {
    puts ">>> 内核仍未探测到 UART"
}

# 可选:注入故障。
#
# 用法: xsdb run_kernel_uart.tcl <selector>
#   1 = Data Abort   2 = Undefined Instruction   3 = Prefetch Abort
#
# 放在最后是有意的:只有先确认内核正常跑起来了,注入才有意义 ——
# 否则"触发了异常"和"内核本来就没起来"在串口上长得一样。
set sel [lindex $argv 0]
if {$sel ne "" && $sel != 0} {
    step "注入故障 selector=$sel"
    mwr -force 0x00020080 $sel
    puts "已写入 FAULT_SEL"

    # 异常处理函数会打完现场再停机,9600 波特下需要一点时间把日志吐完
    after 4000

    puts "FAULT_SEL  = [rd 0x00020080]  (内核应已清零,避免反复触发)"
    puts "PC         = [rr pc]"
    puts "DFAR       = [rr dfar]"
    puts "DFSR       = [rr dfsr]"
    puts "IFAR       = [rr ifar]"
    puts "IFSR       = [rr ifsr]"
}
exit 0
